# code that explains dict keys. keys shortened for readability of complete file
[code]
serial_number = "s"
transmitter_type = "t"
tag_id = "i"
frequency = "f"
duty_sec = "d"
protocol = "p"
auto_off_after_start = "a"
cage_name = "cn"
conversion_factor = "cf"
commentrange_etc = "cr"
data_type = "dt"
tbr = "tbr"

# tbr serial ids with matching depths
[cages]


# metadata for tags in project
[metadata]
